source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'ziya', '2.3.0'
gem 'color'
gem 'logging'
gem 'builder'
gem 'rails-erd'
gem 'mysql2'
gem 'rspec-rails', '>= 2.0.0'
gem "haml"
gem "haml-rails"
gem "jquery-rails"
#gem "calendar_helper", :git => 'git://github.com/AaronH/calendar_helper.git'
#gem "ibox-rails-plugin", :git => 'git://github.com/vanntastic/ibox-rails-plugin.git', :branch => 'rails_3'
gem 'tabs_on_rails'
#gem "jquery_ui_rails_helpers", :git => 'git://github.com/beardedstudio/jquery_ui_rails_helpers.git'
#'git://github.com/CodeOfficer/jquery-ui-rails-helpers.git'
gem 'twitter-auth', :require => 'twitter_auth/engine', :path => 'vendor/git/twitter-auth', :branch => 'rails_3'
gem 'json'
# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
